import type { Token, TokenGroup } from "./types";
import { utilitiesForToken } from "./utilities";

export interface ManifestToken {
  name: string;
  group: TokenGroup;
  values: { light?: string; dark?: string };
  utilities: string[];
  usage?: string;
}
export interface Manifest {
  generatedFrom: string;
  tokens: ManifestToken[];
}

const GROUP_ORDER: TokenGroup[] = [
  "color", "fontFamily", "fontSize", "lineHeight", "fontWeight",
  "spacing", "radius", "borderWidth", "shadow", "duration", "easing",
  "zIndex", "opacity", "container",
];

function mergeByName(tokens: Token[], radiusSteps?: string[]): ManifestToken[] {
  const byName = new Map<string, ManifestToken>();
  for (const t of tokens) {
    let entry = byName.get(t.name);
    if (!entry) {
      const hint = utilitiesForToken(t, t.group === "radius" ? radiusSteps : undefined);
      entry = {
        name: t.name,
        group: t.group,
        values: {},
        utilities: hint.utilities,
        ...(hint.usage ? { usage: hint.usage } : {}),
      };
      byName.set(t.name, entry);
    }
    entry.values[t.theme] = t.value;
  }
  // deterministic: group order, then name
  return [...byName.values()].sort((a, b) => {
    const g = GROUP_ORDER.indexOf(a.group) - GROUP_ORDER.indexOf(b.group);
    return g !== 0 ? g : a.name.localeCompare(b.name);
  });
}

const PREAMBLE = `# Design System — token reference

> **Generated from \`app/globals.css\`. Do not edit this file by hand — run \`npm run tokens\`.**

## Usage rules
- Style with the Tailwind utilities in the **Utilities** column below (\`bg-primary\`, \`text-lg\`, \`p-4\`, \`rounded-lg\`).
- **Never hardcode** a color / size / font / duration, and **never use a non-token Tailwind class** like \`bg-red-500\` or \`text-[#abc]\`. Off-token color & type classes produce **no styles** (the namespace is cleared) — your element renders unstyled, and a blocking lint will reject them.
- Components live in \`components/ui/\` (shadcn: \`Button\`, \`Card\`/\`CardHeader\`/\`CardContent\`/\`CardFooter\`, \`Input\`, …). Import and compose them; they are already token-themed.

## Extension procedure (add a value the system lacks)
One procedure for everything: **add the value token to \`:root\` in \`app/globals.css\`, then run \`npm run tokens\`** — it auto-wires the Tailwind utility and refreshes this manifest. **Never hardcode; never use an off-scale class** (it produces no styles and the blocking lint rejects it). **If no existing token fits the *meaning* (not just the syntax), extend — don't repurpose a semantically-wrong token (e.g. \`warning\` for a celebratory promo).**

**Color — extend freely** (the common case). Add to BOTH \`:root\` and \`.dark\` (plus a \`<name>-foreground\` partner if text sits on it):

\`\`\`css
/* in :root */   --highlight: oklch(0.72 0.18 320); --highlight-foreground: oklch(0.99 0 0);
/* in .dark */   --highlight: oklch(0.66 0.18 320); --highlight-foreground: oklch(0.16 0 0);
\`\`\`
then \`npm run tokens\` → use \`bg-highlight text-highlight-foreground\`.
**The \`<name>\`/\`<name>-foreground\` pair must clear WCAG-AA contrast** (4.5:1, or 3:1 for large/muted text) in **both** blocks, or \`npm run check\` fails.

**Scales (type / shadow / weight) — the ramp is deliberately small; reach for an existing step FIRST.** Only when the ramp genuinely can't express what you need, add the value token (the **value-token name differs from the utility name** — get it wrong and it silently won't wire):
- shadow: \`--elevation-<step>\` → \`shadow-<step>\`
- font size: \`--fs-<step>\` **and** its \`--lh-<step>\` pair → \`text-<step>\`
- font weight: \`--fw-<step>\` → \`font-<step>\`

\`\`\`css
/* in :root */  --elevation-xl: 0 20px 25px -5px oklch(0 0 0 / 0.1), 0 8px 10px -6px oklch(0 0 0 / 0.1);
\`\`\`
then \`npm run tokens\` → use \`shadow-xl\`.

**Roundness & spacing are KNOBS — radius is NOT like the other scales.** To make corners rounder/softer, **increase \`--radius\`** (e.g. \`0.625rem\` → \`1rem\`) then \`npm run tokens\` — it shifts every step. **Do NOT reach for \`rounded-2xl\`/\`rounded-3xl\`** (cleared namespace → no CSS → the gate rejects it). For spacing density, edit \`--spacing-base\`. Only add a \`--radius-<step>\` to the \`@theme\` block (not \`:root\`) for a genuine one-off extra step.

**Token names are a contract** (kebab-case; \`<name>-foreground\` pairs; the \`--fs-\`/\`--lh-\`/\`--elevation-\`/\`--fw-\` value-token prefixes for scales). Full rules in \`docs/NAMING-CONVENTION.md\`.
`;

function markdownTable(tokens: ManifestToken[]): string {
  const rows = tokens.map((t) => {
    const util = t.utilities.length ? t.utilities.join(" ") : (t.usage ?? "");
    const value = t.values.dark
      ? `\`${t.values.light ?? ""}\` / \`${t.values.dark}\``
      : `\`${t.values.light ?? ""}\``;
    return `| \`${t.name}\` | ${t.group} | ${value} | ${util} |`;
  });
  return ["| Token | Group | Value (light / dark) | Utilities |", "|---|---|---|---|", ...rows].join("\n");
}

export function buildManifest(tokens: Token[], source = "app/globals.css", radiusSteps?: string[]): { json: Manifest; markdown: string } {
  const merged = mergeByName(tokens, radiusSteps);
  const json: Manifest = { generatedFrom: source, tokens: merged };
  const markdown = `${PREAMBLE}\n## Tokens\n\n${markdownTable(merged)}\n`;
  return { json, markdown };
}
