import type { Token, TokenGroup } from "./types";
import { utilitiesForToken } from "./utilities";

export interface ManifestToken {
  name: string;
  group: TokenGroup;
  values: { light?: string; dark?: string };
  utilities: string[];
  usage?: string;
}
export interface Manifest {
  generatedFrom: string;
  tokens: ManifestToken[];
}

const GROUP_ORDER: TokenGroup[] = [
  "color", "fontFamily", "fontSize", "lineHeight", "fontWeight",
  "spacing", "radius", "borderWidth", "shadow", "duration", "easing",
  "zIndex", "opacity", "container",
];

function mergeByName(tokens: Token[]): ManifestToken[] {
  const byName = new Map<string, ManifestToken>();
  for (const t of tokens) {
    let entry = byName.get(t.name);
    if (!entry) {
      const hint = utilitiesForToken(t);
      entry = {
        name: t.name,
        group: t.group,
        values: {},
        utilities: hint.utilities,
        ...(hint.usage ? { usage: hint.usage } : {}),
      };
      byName.set(t.name, entry);
    }
    entry.values[t.theme] = t.value;
  }
  // deterministic: group order, then name
  return [...byName.values()].sort((a, b) => {
    const g = GROUP_ORDER.indexOf(a.group) - GROUP_ORDER.indexOf(b.group);
    return g !== 0 ? g : a.name.localeCompare(b.name);
  });
}

const PREAMBLE = `# Design System — token reference

> **Generated from \`app/globals.css\`. Do not edit this file by hand — run \`npm run tokens\`.**

## Usage rules
- Style with the Tailwind utilities in the **Utilities** column below (\`bg-primary\`, \`text-lg\`, \`p-4\`, \`rounded-lg\`).
- **Never hardcode** a color / size / font / duration, and **never use a non-token Tailwind class** like \`bg-red-500\` or \`text-[#abc]\`. Off-token color & type classes produce **no styles** (the namespace is cleared) — your element renders unstyled, and a blocking lint will reject them.
- Components live in \`components/ui/\` (shadcn: \`Button\`, \`Card\`/\`CardHeader\`/\`CardContent\`/\`CardFooter\`, \`Input\`, …). Import and compose them; they are already token-themed.

## Extension procedure (add a value the system lacks)
**For a color** (the common case): add the token to BOTH \`:root\` and \`.dark\` in \`app/globals.css\` with an \`oklch(...)\` value (and a \`-foreground\` partner if it needs readable text on top), then run \`npm run tokens\`. That one command **auto-wires the Tailwind utility for you** (\`bg-<name>\`, \`text-<name>\`, \`border-<name>\`) and refreshes this manifest. Use it. **Never hardcode.** Example:

\`\`\`css
/* in :root */   --highlight: oklch(0.72 0.18 320); --highlight-foreground: oklch(0.99 0 0);
/* in .dark */   --highlight: oklch(0.66 0.18 320); --highlight-foreground: oklch(0.16 0 0);
\`\`\`
then \`npm run tokens\` → use \`bg-highlight text-highlight-foreground\`.

**Token names are a contract.** Use kebab-case; pair foreground colors as \`<name>-foreground\`; follow the existing patterns in the table. A color is recognised by its \`oklch(...)\` value, so you don't edit any config — just add it and run \`npm run tokens\`. (Non-color scales like type/shadow are fixed; adding to those is rare and documented in \`docs/NAMING-CONVENTION.md\`.)
`;

function markdownTable(tokens: ManifestToken[]): string {
  const rows = tokens.map((t) => {
    const util = t.utilities.length ? t.utilities.join(" ") : (t.usage ?? "");
    const value = t.values.dark
      ? `\`${t.values.light ?? ""}\` / \`${t.values.dark}\``
      : `\`${t.values.light ?? ""}\``;
    return `| \`${t.name}\` | ${t.group} | ${value} | ${util} |`;
  });
  return ["| Token | Group | Value (light / dark) | Utilities |", "|---|---|---|---|", ...rows].join("\n");
}

export function buildManifest(tokens: Token[], source = "app/globals.css"): { json: Manifest; markdown: string } {
  const merged = mergeByName(tokens);
  const json: Manifest = { generatedFrom: source, tokens: merged };
  const markdown = `${PREAMBLE}\n## Tokens\n\n${markdownTable(merged)}\n`;
  return { json, markdown };
}
