import type { CatalogEntry } from "./registry";

/** Deterministic markdown — the LLM-facing component catalog. Stable order = the array order. */
export function buildCatalogMarkdown(catalog: CatalogEntry[]): string {
  const lines: string[] = [
    "# Component Catalog",
    "",
    "Generated by `npm run catalog` from `lib/catalog/registry.ts`. Do not edit by hand.",
    "",
    "These primitives already exist in `components/ui/*` — **import and use them; do not hand-roll equivalents.** All are token-only and accessible by default.",
    "",
  ];
  for (const e of catalog) {
    lines.push(`## ${e.name}`);
    lines.push("");
    lines.push(`- **Purpose:** ${e.purpose}`);
    lines.push(`- **When to use:** ${e.whenToUse}`);
    lines.push(`- **Exports:** ${e.exports.join(", ")}`);
    lines.push("");
    lines.push("```tsx");
    lines.push(e.import);
    lines.push("");
    lines.push(e.snippet);
    lines.push("```");
    lines.push("");
  }
  return lines.join("\n");
}
