export type CatalogEntry = {
  name: string;        // logical primitive
  file: string;        // components/ui path
  exports: string[];   // every Capitalized export the file provides
  purpose: string;     // one line — what it's for
  whenToUse: string;   // when to reach for it
  import: string;      // copy-paste import line
  snippet: string;     // minimal usage
};

export const CATALOG: CatalogEntry[] = [
  { name: "Button", file: "components/ui/button.tsx", exports: ["Button"],
    purpose: "Clickable action — variants (default/secondary/outline/ghost/destructive/link) + sizes.",
    whenToUse: "Any action or submit. Use asChild to render a link as a button.",
    import: `import { Button } from "@/components/ui/button"`,
    snippet: `<Button variant="outline">Save</Button>` },
  { name: "Input", file: "components/ui/input.tsx", exports: ["Input"],
    purpose: "Single-line text field.",
    whenToUse: "Short text/email/number entry. Pair with Label.",
    import: `import { Input } from "@/components/ui/input"`,
    snippet: `<Input type="email" placeholder="you@example.com" />` },
  { name: "Card", file: "components/ui/card.tsx",
    exports: ["Card", "CardHeader", "CardTitle", "CardAction", "CardDescription", "CardContent", "CardFooter"],
    purpose: "Surface container with header/title/description/content/footer slots.",
    whenToUse: "Group related content into a panel.",
    import: `import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"`,
    snippet: `<Card><CardHeader><CardTitle>Plan</CardTitle></CardHeader><CardContent>…</CardContent></Card>` },
  { name: "Avatar", file: "components/ui/avatar.tsx",
    exports: ["Avatar", "AvatarImage", "AvatarFallback", "AvatarGroup"],
    purpose: "User image with initials fallback; AvatarGroup stacks with a +N overflow chip.",
    whenToUse: "Represent a person. Always give Avatar an aria-label (the name).",
    import: `import { Avatar, AvatarFallback } from "@/components/ui/avatar"`,
    snippet: `<Avatar aria-label="Jane Doe"><AvatarFallback aria-hidden>JD</AvatarFallback></Avatar>` },
  { name: "Badge", file: "components/ui/badge.tsx", exports: ["Badge"],
    purpose: "Small status/label pill — semantic variants (success/warning/info/destructive/…).",
    whenToUse: "Status or category. The label text must carry the meaning (never color alone).",
    import: `import { Badge } from "@/components/ui/badge"`,
    snippet: `<Badge variant="success">Done</Badge>` },
  { name: "Separator", file: "components/ui/separator.tsx", exports: ["Separator"],
    purpose: "Horizontal or vertical divider rule.",
    whenToUse: "Separate groups of content or toolbar items.",
    import: `import { Separator } from "@/components/ui/separator"`,
    snippet: `<Separator orientation="vertical" />` },
  { name: "Code", file: "components/ui/code.tsx", exports: ["Code", "Kbd"],
    purpose: "Code: inline <code> chip. Kbd: keyboard-cap glyph (uses the 2xs micro step).",
    whenToUse: "Inline command/code (Code) or a shortcut key (Kbd).",
    import: `import { Code, Kbd } from "@/components/ui/code"`,
    snippet: `Run <Code>npm run dev</Code> or press <Kbd>⌘</Kbd> <Kbd>K</Kbd>` },
  { name: "Dialog", file: "components/ui/dialog.tsx",
    exports: ["Dialog","DialogTrigger","DialogPortal","DialogClose","DialogOverlay","DialogContent","DialogHeader","DialogFooter","DialogTitle","DialogDescription"],
    purpose: "Modal dialog over a dimmed (--overlay) scrim.",
    whenToUse: "Confirmations, short forms, focused tasks. Always include a DialogTitle (a11y).",
    import: `import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"`,
    snippet: `<Dialog><DialogTrigger>Open</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Are you sure?</DialogTitle></DialogHeader></DialogContent></Dialog>` },
  { name: "AlertDialog", file: "components/ui/alert-dialog.tsx",
    exports: ["AlertDialog","AlertDialogTrigger","AlertDialogContent","AlertDialogHeader","AlertDialogFooter","AlertDialogTitle","AlertDialogDescription","AlertDialogAction","AlertDialogCancel"],
    purpose: "Confirm a destructive/irreversible action (action + cancel).",
    whenToUse: "Destructive confirmations (delete, discard). Blocks until the user chooses; always include a title.",
    import: `import { AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@/components/ui/alert-dialog"`,
    snippet: `<AlertDialog><AlertDialogTrigger>Delete</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete?</AlertDialogTitle></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>` },
  { name: "Sheet", file: "components/ui/sheet.tsx",
    exports: ["Sheet","SheetTrigger","SheetClose","SheetContent","SheetHeader","SheetFooter","SheetTitle","SheetDescription"],
    purpose: "Side panel (drawer) sliding in from an edge over the --overlay scrim — top/right/bottom/left.",
    whenToUse: "Secondary tasks, filters, or nav that shouldn't replace the page. Set side; include a SheetTitle.",
    import: `import { Sheet, SheetTrigger, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"`,
    snippet: `<Sheet><SheetTrigger>Open</SheetTrigger><SheetContent side="right"><SheetHeader><SheetTitle>Filters</SheetTitle></SheetHeader></SheetContent></Sheet>` },
  { name: "Popover", file: "components/ui/popover.tsx",
    exports: ["Popover","PopoverTrigger","PopoverAnchor","PopoverContent"],
    purpose: "Floating panel anchored to a trigger (non-modal).",
    whenToUse: "Rich content on click — pickers, forms, extra detail. For plain hover hints use Tooltip; for menus use DropdownMenu.",
    import: `import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"`,
    snippet: `<Popover><PopoverTrigger>Open</PopoverTrigger><PopoverContent>Panel content</PopoverContent></Popover>` },
  { name: "Tooltip", file: "components/ui/tooltip.tsx",
    exports: ["Tooltip","TooltipTrigger","TooltipContent","TooltipProvider"],
    purpose: "Brief hover/focus hint anchored to a trigger.",
    whenToUse: "Label an icon-only control or add a short hint. Not for rich/interactive content (use Popover). Keep it terse.",
    import: `import { Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip"`,
    snippet: `<Tooltip><TooltipTrigger>?</TooltipTrigger><TooltipContent>Helpful hint</TooltipContent></Tooltip>` },
];
