export type CatalogEntry = {
  name: string;        // logical primitive
  file: string;        // components/ui path
  exports: string[];   // every Capitalized export the file provides
  purpose: string;     // one line — what it's for
  whenToUse: string;   // when to reach for it
  import: string;      // copy-paste import line
  snippet: string;     // minimal usage
};

export const CATALOG: CatalogEntry[] = [
  { name: "Button", file: "components/ui/button.tsx", exports: ["Button"],
    purpose: "Clickable action — variants (default/secondary/outline/ghost/destructive/link) + sizes.",
    whenToUse: "Any action or submit. Use asChild to render a link as a button.",
    import: `import { Button } from "@/components/ui/button"`,
    snippet: `<Button variant="outline">Save</Button>` },
  { name: "Input", file: "components/ui/input.tsx", exports: ["Input"],
    purpose: "Single-line text field.",
    whenToUse: "Short text/email/number entry. Pair with Label.",
    import: `import { Input } from "@/components/ui/input"`,
    snippet: `<Input type="email" placeholder="you@example.com" />` },
  { name: "Card", file: "components/ui/card.tsx",
    exports: ["Card", "CardHeader", "CardTitle", "CardAction", "CardDescription", "CardContent", "CardFooter"],
    purpose: "Surface container with header/title/description/content/footer slots.",
    whenToUse: "Group related content into a panel.",
    import: `import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"`,
    snippet: `<Card><CardHeader><CardTitle>Plan</CardTitle></CardHeader><CardContent>…</CardContent></Card>` },
  { name: "Avatar", file: "components/ui/avatar.tsx",
    exports: ["Avatar", "AvatarImage", "AvatarFallback", "AvatarGroup"],
    purpose: "User image with initials fallback; AvatarGroup stacks with a +N overflow chip.",
    whenToUse: "Represent a person. Always give Avatar an aria-label (the name).",
    import: `import { Avatar, AvatarFallback } from "@/components/ui/avatar"`,
    snippet: `<Avatar aria-label="Jane Doe"><AvatarFallback aria-hidden>JD</AvatarFallback></Avatar>` },
  { name: "Badge", file: "components/ui/badge.tsx", exports: ["Badge"],
    purpose: "Small status/label pill — semantic variants (success/warning/info/destructive/…).",
    whenToUse: "Status or category. The label text must carry the meaning (never color alone).",
    import: `import { Badge } from "@/components/ui/badge"`,
    snippet: `<Badge variant="success">Done</Badge>` },
  { name: "Separator", file: "components/ui/separator.tsx", exports: ["Separator"],
    purpose: "Horizontal or vertical divider rule.",
    whenToUse: "Separate groups of content or toolbar items.",
    import: `import { Separator } from "@/components/ui/separator"`,
    snippet: `<Separator orientation="vertical" />` },
  { name: "Code", file: "components/ui/code.tsx", exports: ["Code", "Kbd"],
    purpose: "Code: inline <code> chip. Kbd: keyboard-cap glyph (uses the 2xs micro step).",
    whenToUse: "Inline command/code (Code) or a shortcut key (Kbd).",
    import: `import { Code, Kbd } from "@/components/ui/code"`,
    snippet: `Run <Code>npm run dev</Code> or press <Kbd>⌘</Kbd> <Kbd>K</Kbd>` },
  { name: "Dialog", file: "components/ui/dialog.tsx",
    exports: ["Dialog","DialogTrigger","DialogPortal","DialogClose","DialogOverlay","DialogContent","DialogHeader","DialogFooter","DialogTitle","DialogDescription"],
    purpose: "Modal dialog over a dimmed (--overlay) scrim.",
    whenToUse: "Confirmations, short forms, focused tasks. Always include a DialogTitle (a11y).",
    import: `import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"`,
    snippet: `<Dialog><DialogTrigger>Open</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Are you sure?</DialogTitle></DialogHeader></DialogContent></Dialog>` },
  { name: "AlertDialog", file: "components/ui/alert-dialog.tsx",
    exports: ["AlertDialog","AlertDialogTrigger","AlertDialogContent","AlertDialogHeader","AlertDialogFooter","AlertDialogTitle","AlertDialogDescription","AlertDialogAction","AlertDialogCancel"],
    purpose: "Confirm a destructive/irreversible action (action + cancel).",
    whenToUse: "Destructive confirmations (delete, discard). Blocks until the user chooses; always include a title.",
    import: `import { AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogAction, AlertDialogCancel } from "@/components/ui/alert-dialog"`,
    snippet: `<AlertDialog><AlertDialogTrigger>Delete</AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete?</AlertDialogTitle></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction>Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>` },
  { name: "Sheet", file: "components/ui/sheet.tsx",
    exports: ["Sheet","SheetTrigger","SheetClose","SheetContent","SheetHeader","SheetFooter","SheetTitle","SheetDescription"],
    purpose: "Side panel (drawer) sliding in from an edge over the --overlay scrim — top/right/bottom/left.",
    whenToUse: "Secondary tasks, filters, or nav that shouldn't replace the page. Set side; include a SheetTitle.",
    import: `import { Sheet, SheetTrigger, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet"`,
    snippet: `<Sheet><SheetTrigger>Open</SheetTrigger><SheetContent side="right"><SheetHeader><SheetTitle>Filters</SheetTitle></SheetHeader></SheetContent></Sheet>` },
  { name: "Popover", file: "components/ui/popover.tsx",
    exports: ["Popover","PopoverTrigger","PopoverAnchor","PopoverContent"],
    purpose: "Floating panel anchored to a trigger (non-modal).",
    whenToUse: "Rich content on click — pickers, forms, extra detail. For plain hover hints use Tooltip; for menus use DropdownMenu.",
    import: `import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"`,
    snippet: `<Popover><PopoverTrigger>Open</PopoverTrigger><PopoverContent>Panel content</PopoverContent></Popover>` },
  { name: "Tooltip", file: "components/ui/tooltip.tsx",
    exports: ["Tooltip","TooltipTrigger","TooltipContent","TooltipProvider"],
    purpose: "Brief hover/focus hint anchored to a trigger.",
    whenToUse: "Label an icon-only control or add a short hint. Not for rich/interactive content (use Popover). Keep it terse.",
    import: `import { Tooltip, TooltipTrigger, TooltipContent } from "@/components/ui/tooltip"`,
    snippet: `<Tooltip><TooltipTrigger>?</TooltipTrigger><TooltipContent>Helpful hint</TooltipContent></Tooltip>` },
  { name: "DropdownMenu", file: "components/ui/dropdown-menu.tsx",
    exports: ["DropdownMenu","DropdownMenuTrigger","DropdownMenuGroup","DropdownMenuContent","DropdownMenuItem","DropdownMenuCheckboxItem","DropdownMenuRadioGroup","DropdownMenuRadioItem","DropdownMenuLabel","DropdownMenuSeparator","DropdownMenuShortcut"],
    purpose: "Menu of actions/options anchored to a trigger — items, checkbox/radio items, labels, separators, shortcuts.",
    whenToUse: "Action menus (row actions, account menu, overflow). For form selection use Select; for rich panels use Popover.",
    import: `import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"`,
    snippet: `<DropdownMenu><DropdownMenuTrigger>Open</DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem>Profile</DropdownMenuItem></DropdownMenuContent></DropdownMenu>` },
  { name: "Label", file: "components/ui/label.tsx", exports: ["Label"],
    purpose: "Accessible caption for a form control.",
    whenToUse: "Always label inputs. Set htmlFor to the control id (or wrap the control). Pairs with Input/Textarea/Select/Checkbox.",
    import: `import { Label } from "@/components/ui/label"`,
    snippet: `<Label htmlFor="email">Email</Label>` },
  { name: "Checkbox", file: "components/ui/checkbox.tsx", exports: ["Checkbox"],
    purpose: "Binary on/off toggle for a single option.",
    whenToUse: "Opt-ins, multi-select lists, 'I agree' boxes. Pair with a Label (htmlFor). For mutually-exclusive choices use RadioGroup; for an instant setting use Switch.",
    import: `import { Checkbox } from "@/components/ui/checkbox"`,
    snippet: `<Checkbox id="terms" defaultChecked />` },
  { name: "RadioGroup", file: "components/ui/radio-group.tsx", exports: ["RadioGroup","RadioGroupItem"],
    purpose: "Pick exactly one option from a small set.",
    whenToUse: "2–5 mutually-exclusive choices, all visible. Pair each item with a Label. For many options use Select; for multi-select use Checkbox.",
    import: `import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group"`,
    snippet: `<RadioGroup defaultValue="a"><RadioGroupItem value="a" id="a" /><RadioGroupItem value="b" id="b" /></RadioGroup>` },
  { name: "Switch", file: "components/ui/switch.tsx", exports: ["Switch"],
    purpose: "Instant on/off toggle for a setting (applies immediately).",
    whenToUse: "Settings that take effect at once (notifications, dark mode). For form submit-time selection use Checkbox. Pair with a Label.",
    import: `import { Switch } from "@/components/ui/switch"`,
    snippet: `<Switch id="notify" defaultChecked />` },
  { name: "Select", file: "components/ui/select.tsx",
    exports: ["Select","SelectGroup","SelectValue","SelectTrigger","SelectContent","SelectLabel","SelectItem","SelectSeparator"],
    purpose: "Choose one option from a dropdown list (token-styled native-feel select).",
    whenToUse: "One choice from many (6+). For 2–5 visible options use RadioGroup; for actions use DropdownMenu. Give the SelectValue a placeholder.",
    import: `import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"`,
    snippet: `<Select><SelectTrigger><SelectValue placeholder="Pick" /></SelectTrigger><SelectContent><SelectItem value="a">A</SelectItem></SelectContent></Select>` },
  { name: "Textarea", file: "components/ui/textarea.tsx", exports: ["Textarea"],
    purpose: "Multi-line text field.",
    whenToUse: "Longer free-form text (comments, descriptions). For single-line use Input. Pair with a Label.",
    import: `import { Textarea } from "@/components/ui/textarea"`,
    snippet: `<Textarea placeholder="Add a note…" />` },
  { name: "Tabs", file: "components/ui/tabs.tsx",
    exports: ["Tabs", "TabsList", "TabsTrigger", "TabsContent"],
    purpose: "Switch between panels of content within the same view.",
    whenToUse: "Segment related content under one heading. For navigation between pages use links, not Tabs.",
    import: `import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"`,
    snippet: `<Tabs defaultValue="a"><TabsList><TabsTrigger value="a">A</TabsTrigger><TabsTrigger value="b">B</TabsTrigger></TabsList><TabsContent value="a">…</TabsContent><TabsContent value="b">…</TabsContent></Tabs>` },
];
